apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin-node
  labels:
    app: bitcoin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bitcoin
  template:
    metadata:
      labels:
        app: bitcoin
    spec:
      containers:
      - name: bitcoin-node
        image: sashvazquez/bitcoin-node:latest
        ports:
        - containerPort: 8000
        env:
        - name: RUST_LOG
          value: "info"